# Generated by Django 6.0.2 on 2026-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("tools", "Tools"),
                    ("home", "Home"),
                    ("outdoors", "Outdoors"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
